name: deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - run: yarn install
      - run: yarn build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_TOKEN }}
          force_orphan: true
          publish_branch: gh-pages
          publish_dir: ./out