name: deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - run: yarn install
      - run: yarn build

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out